//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{


    public partial class Productos
    {

        public global::System.Web.UI.WebControls.GridView GridViewTable;

        public global::System.Web.UI.WebControls.TextBox TbBuscar;

        public global::System.Web.UI.WebControls.TextBox TbNombreProductoSave;
        public global::System.Web.UI.WebControls.TextBox TbDescripcionSave;
        public global::System.Web.UI.WebControls.TextBox TbPrecioSave;

        public global::System.Web.UI.WebControls.TextBox TbCodigoUpdate;
        public global::System.Web.UI.WebControls.TextBox TbNombreProductoUpdate;
        public global::System.Web.UI.WebControls.TextBox TbDescripcionUpdate;
        public global::System.Web.UI.WebControls.TextBox TbPrecioUpdate;

        public global::System.Web.UI.WebControls.TextBox TbCodigoDelete;
        public global::System.Web.UI.WebControls.Label LbNombreProductoDelete;

        public global::System.Web.UI.WebControls.DropDownList DropDownMarcaSave;
        public global::System.Web.UI.WebControls.DropDownList DropDownCategoriaSave;
        public global::System.Web.UI.WebControls.DropDownList DropDownAlmacenSave;
        public global::System.Web.UI.WebControls.DropDownList DropDownMonedaSave;

        public global::System.Web.UI.WebControls.DropDownList DropDownMarcaUpdate;
        public global::System.Web.UI.WebControls.DropDownList DropDownCategoriaUpdate;
        public global::System.Web.UI.WebControls.DropDownList DropDownAlmacenUpdate;
        public global::System.Web.UI.WebControls.DropDownList DropDownMonedaUpdate;

        public global::System.Web.UI.WebControls.DropDownList DropDownLimite;
        public global::System.Web.UI.WebControls.DropDownList DropDownPagina;
    }
}
