//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{


    public partial class Roles
    {
        public global::System.Web.UI.WebControls.GridView GridViewTable;

        public global::System.Web.UI.WebControls.TextBox TbBuscar;

        public global::System.Web.UI.WebControls.TextBox TbNombreSave;

        public global::System.Web.UI.WebControls.TextBox TbCodigoUpdate;
        public global::System.Web.UI.WebControls.TextBox TbNombreUpdate;

        public global::System.Web.UI.WebControls.TextBox TbCodigoDelete;
        public global::System.Web.UI.WebControls.Label LbNombreDelete;


        public global::System.Web.UI.WebControls.DropDownList DropDownLimite;
        public global::System.Web.UI.WebControls.DropDownList DropDownPagina;
    }
}
