//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{


    public partial class Usuarios
    {
        public global::System.Web.UI.WebControls.Label NombreUsuarioLabel;
        public global::System.Web.UI.WebControls.Table Table1;

    }
}
